### ISSUE TITLE
beret actually has spec_skin1 and spec_headcrash1 in the latest OA svn

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint-patch-data#1]
It turns out that I looked in there not too long ago & there, in fact, seems to be the files you patched out with dummy files in Spearmint. I will merge them in with my next pull request.
I'm probably gonna reference the main Spearmint issue I posted:
https://github.com/zturtleman/spearmint/issues/231

**Comment by zturtleman** [comment]
Let's only use one issue tracker. Disabling issue tracker for spearmint-patch-data.
